### ISSUE TITLE
The application isn't showing control anymore

### ISSUE THREAD

**Issue by removogel** [justinforlenza/keylight-control#16]
Keylight Control worked very fine for 30 minutes after install . The i created a launcher entry for the AppImage and started it maybe a few times and had more than one instance running. 
Now (even after system reboot) the application window stays empty, see screenshot. 
At the same time i can still control the light via iOS app. 

![image](https://user-images.githubusercontent.com/8896037/154811157-41e5fcb9-4bca-43ac-9924-b88bcbdd6724.png)

When starting from CMD i get following error

```
'/home/user/Apps/Keylight_Controller-x86_64.AppImage' 
Welcome to Node.js v14.2.0.
Type ".help" for more information.
> (node:6403) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Keylight_Controller-x86_64.AppImage --trace-deprecation ...` to show where the warning was created)
> 

```

This is the launcher code, but this should't be the problem
```
[Desktop Entry]
Name=KeyLightControl
Comment=Elgato Keylight Controller
Exec=/home/user/Apps/Keylight_Controller-x86_64.AppImage
Icon=elgato
Terminal=false
Type=Application
Categories=Education;
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - Version: KeylightController 0.1.6

**Comment by removogel** [comment]
Did a reset of Keylights - no effect. 

Deactivated Portmaster firewall - no effect. 

I'am able to ping the lights. 

But regarding the firewall, the concept of app images is not clear to me. With every start, a new instance is created under a new path. Since the binary paths are always different, I cannot enable them in the firewall. Which means, this app can't be safely used in a firewall setup. Is this correct or have I misunderstood something here?

**Comment by justinforlenza** [comment]
Was it originally working without the firewall? 

And as far as firewalls, are you specifically whitelisting _outbound_ connections, or just inbound?

**Comment by removogel** [comment]
It's a firewall issue, not a bug! Sorry Justin!

At my general setting i just whitelist inbound. After explicit whitelisting the Elgato-IP in&out systemwide it works again.
I was toggling now in/out-rules for a while and checking with this Bash (could be a solution for Issue14)
https://github.com/endocrimes/keylightctl
./keylightctl discover

At my system these generic host like elgato-key-light-air-65ca.local arn't working. 
Had a look over your code. How do you get the IP of the light?

**Comment by justinforlenza** [comment]
>It's a firewall issue, not a bug! Sorry Justin!

Great to hear you were able to figure that out and dont worry about it

> https://github.com/endocrimes/keylightctl

Oh awesome! i'll mention that in #14 until i'm able to add a CLI into the app itself

>Had a look over your code. How do you get the IP of the light?

The application uses Bonjour to find keylights on the local network. ([src/index.js#L172-L178](https://github.com/justinforlenza/keylight-control/blob/main/src/index.js#L172-L178))

**Comment by removogel** [comment]
Thanks. I have to read a bit about these zeroconf magic :-)

**Comment by justinforlenza** [comment]
Yeah no problem. 

I have been wanting to add a manual entry of an IP address (because even the best of times Bonjour can still be flakey), but haven't had the bandwidth to implement it. 

As of right now the discovered key lights are stored in memory and I would need to implement some form of persistent storage first to support manual IP/Hostname addition so that you don't have to re-add every launch.

**Comment by justinforlenza** [comment]
Going to close out this ticket, and track the new feature in #17
